name: Continuous Integration

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    - cron:  0 10 * * 1-5

jobs:
  audit:
    name: NPM Audit (Production)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npx panva/npm-install-retry
      - run: npm audit --production

  test:
    name: Node Tests + Coverage
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 12.19.0
          - 12
          - 14.15.0
          - 14
          - 16.13.0
          - 16
        include:
          - experimental: true
            node-version: '>=17'
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Store node version variable
        id: node
        run: |
          echo "::set-output name=version::$(node -v)"
      - name: Cache node_modules
        uses: actions/cache@v2
        id: node_modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package.json') }}-${{ steps.node.outputs.version }}
      - name: Install dependencies
        run: npx panva/npm-install-retry
        if: ${{ steps.node_modules.outputs.cache-hit != 'true' }}
      - run: npm run coverage

  electron:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        electron-version:
          - 12.0.0
          - latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Store node version variable
        id: node
        run: |
          echo "::set-output name=version::$(node -v)"
      - name: Cache node_modules
        uses: actions/cache@v2
        id: node_modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package.json') }}-${{ steps.node.outputs.version }}
      - name: Install dependencies
        run: npx panva/npm-install-retry
        if: ${{ steps.node_modules.outputs.cache-hit != 'true' }}
      - run: npx xvfb-maybe npx electron@${{ matrix.electron-version }} ./test/electron test/**/*.test.js

  build-conformance-suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set Conformance Suite Version
        run: |
          export VERSION=($(curl --silent "https://gitlab.com/api/v4/projects/4175605/releases" | jq -r '.[0].tag_name'))
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Load Cached Conformance Suite Build
        uses: actions/cache@v2
        id: cache
        with:
          path: ./conformance-suite
          key: suite-${{ hashFiles('.github/workflows/test.yml') }}-${{ env.VERSION }}
      - name: Conformance Suite Checkout
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: git clone --depth 1 --single-branch --branch ${{ env.VERSION }} https://gitlab.com/openid/conformance-suite.git
      - name: Conformance Suite Build
        working-directory: ./conformance-suite
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        env:
          MAVEN_CACHE: ./m2
        run: |
          sed -i -e 's/localhost/localhost.emobix.co.uk/g' src/main/resources/application.properties
          sed -i -e 's/-B clean/-B -DskipTests=true/g' builder-compose.yml
          docker-compose -f builder-compose.yml run builder

  conformance-suite:
    runs-on: ubuntu-latest
    needs:
      - audit
      - test
      - electron
      - build-conformance-suite
    env:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      DEBUG: runner,moduleId*
      SUITE_BASE_URL: https://localhost.emobix.co.uk:8443
      PLAN_NAME: ${{ matrix.setup.plan }}
      VARIANT: ${{ toJSON(matrix.setup) }}
    strategy:
      fail-fast: false
      matrix:
        setup:
          # OIDC BASIC
          - plan: oidcc-client-basic-certification-test-plan

          # OIDC IMPLICIT
          - plan: oidcc-client-implicit-certification-test-plan

          # OIDC HYBRID
          - plan: oidcc-client-hybrid-certification-test-plan

          # OIDC CONFIG
          - plan: oidcc-client-config-certification-test-plan

          # OIDC DYNAMIC
          - plan: oidcc-client-dynamic-certification-test-plan

          # FAPI 1.0 ID-2
          - plan: fapi-rw-id2-client-test-plan
            client_auth_type: mtls
          - plan: fapi-rw-id2-client-test-plan
            client_auth_type: private_key_jwt

          # FAPI 1.0 Advanced Final
          - plan: fapi1-advanced-final-client-test-plan
            client_auth_type: private_key_jwt
          - plan: fapi1-advanced-final-client-test-plan
            client_auth_type: mtls
          - plan: fapi1-advanced-final-client-test-plan
            client_auth_type: mtls
            fapi_auth_request_method: pushed
          - plan: fapi1-advanced-final-client-test-plan
            client_auth_type: private_key_jwt
            fapi_auth_request_method: pushed
          - plan: fapi1-advanced-final-client-test-plan
            client_auth_type: mtls
            fapi_response_mode: jarm
          - plan: fapi1-advanced-final-client-test-plan
            client_auth_type: private_key_jwt
            fapi_response_mode: jarm
          - plan: fapi1-advanced-final-client-test-plan
            client_auth_type: mtls
            fapi_auth_request_method: pushed
            fapi_response_mode: jarm
          - plan: fapi1-advanced-final-client-test-plan
            client_auth_type: private_key_jwt
            fapi_auth_request_method: pushed
            fapi_response_mode: jarm
          - plan: fapi1-advanced-final-client-test-plan
            client_auth_type: mtls
            fapi_auth_request_method: pushed
            fapi_response_mode: jarm
            fapi_jarm_type: plain_oauth
          - plan: fapi1-advanced-final-client-test-plan
            client_auth_type: mtls
            fapi_response_mode: jarm
            fapi_jarm_type: plain_oauth
          - plan: fapi1-advanced-final-client-test-plan
            client_auth_type: private_key_jwt
            fapi_auth_request_method: pushed
            fapi_response_mode: jarm
            fapi_jarm_type: plain_oauth
          - plan: fapi1-advanced-final-client-test-plan
            client_auth_type: private_key_jwt
            fapi_response_mode: jarm
            fapi_jarm_type: plain_oauth

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set Conformance Suite Version
        run: |
          export VERSION=($(curl --silent "https://gitlab.com/api/v4/projects/4175605/releases" | jq -r '.[0].tag_name'))
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Load Cached Conformance Suite Build
        uses: actions/cache@v2
        id: cache
        with:
          path: ./conformance-suite
          key: suite-${{ hashFiles('.github/workflows/test.yml') }}-${{ env.VERSION }}
      - name: Abort if Conformance Suite version changed during the CI run.
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        uses: actions/github-script@v6
        with:
          script: |
              core.setFailed('Conformance Suite version changed during the CI run')
      - name: Run Conformance Suite
        working-directory: ./conformance-suite
        run: |
          docker-compose -f docker-compose-dev.yml up -d
          while ! curl -skfail https://localhost.emobix.co.uk:8443/api/runner/available >/dev/null; do sleep 2; done
      - run: git clone --depth 1 --single-branch --branch always-mtls https://github.com/panva/openid-client-certification-suite.git runner
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npx panva/npm-install-retry
        working-directory: ./runner
      - run: npm install ${{ github.repository }}#${{ github.sha }}
        working-directory: ./runner
      - run: npm run test
        working-directory: ./runner
      - name: Upload test artifacts
        uses: actions/upload-artifact@v2
        with:
          path: runner/export-*.zip
          name: ${{ matrix.setup.plan }} failed html results
          if-no-files-found: ignore
        if: ${{ failure() }}
      - name: Upload test logs
        uses: actions/upload-artifact@v2
        with:
          if-no-files-found: warn
          name: ${{ matrix.setup.plan }} runner logs
          path: runner/logs/*.log
        if: ${{ failure() }}
